/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcheterRouteImport } from './routes/acheter'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as CambuseRouteImport } from './routes/cambuse'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContestRouteImport } from './routes/contest'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as InvestirRouteImport } from './routes/investir'
import { Route as KitRouteImport } from './routes/kit'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MethodRouteImport } from './routes/method'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RssEnDotxmlRouteImport } from './routes/rss-en[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeslaRouteImport } from './routes/tesla'
import { Route as TodayRouteImport } from './routes/today'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAssignRouteImport } from './routes/admin.assign'
import { Route as AdminCalibrationRouteImport } from './routes/admin.calibration'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminRejectedRouteImport } from './routes/admin.rejected'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminTranslationsRouteImport } from './routes/admin.translations'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiDeskAssignRouteImport } from './routes/api/desk-assign'
import { Route as ApiDeskFrontPageRouteImport } from './routes/api/desk-front-page'
import { Route as ApiDeskRewriteRouteImport } from './routes/api/desk-rewrite'
import { Route as ApiDeskStoryStatusRouteImport } from './routes/api/desk-story-status'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiPublishRouteImport } from './routes/api/publish'
import { Route as ApiRssPullRouteImport } from './routes/api/rss-pull'
import { Route as ApiScoreRouteImport } from './routes/api/score'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as FeedsSectionDotxmlRouteImport } from './routes/feeds/$section[.]xml'
import { Route as StorySlugRouteImport } from './routes/story.$slug'
import { Route as AdminStoryIdRouteImport } from './routes/admin.story.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcheterRoute = AcheterRouteImport.update({
  id: '/acheter',
  path: '/acheter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const CambuseRoute = CambuseRouteImport.update({
  id: '/cambuse',
  path: '/cambuse',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRoute = ContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestirRoute = InvestirRouteImport.update({
  id: '/investir',
  path: '/investir',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RssEnDotxmlRoute = RssEnDotxmlRouteImport.update({
  id: '/rss-en.xml',
  path: '/rss-en.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeslaRoute = TeslaRouteImport.update({
  id: '/tesla',
  path: '/tesla',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignRoute = AdminAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalibrationRoute = AdminCalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRejectedRoute = AdminRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskAssignRoute = ApiDeskAssignRouteImport.update({
  id: '/api/desk-assign',
  path: '/api/desk-assign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskFrontPageRoute = ApiDeskFrontPageRouteImport.update({
  id: '/api/desk-front-page',
  path: '/api/desk-front-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRewriteRoute = ApiDeskRewriteRouteImport.update({
  id: '/api/desk-rewrite',
  path: '/api/desk-rewrite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskStoryStatusRoute = ApiDeskStoryStatusRouteImport.update({
  id: '/api/desk-story-status',
  path: '/api/desk-story-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRssPullRoute = ApiRssPullRouteImport.update({
  id: '/api/rss-pull',
  path: '/api/rss-pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoreRoute = ApiScoreRouteImport.update({
  id: '/api/score',
  path: '/api/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsSectionDotxmlRoute = FeedsSectionDotxmlRouteImport.update({
  id: '/feeds/$section.xml',
  path: '/feeds/$section.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StorySlugRoute = StorySlugRouteImport.update({
  id: '/story/$slug',
  path: '/story/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoryIdRoute = AdminStoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/about': typeof AboutRoute
  '/acheter': typeof AcheterRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/cambuse': typeof CambuseRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/contest': typeof ContestRoute
  '/cookies': typeof CookiesRoute
  '/corrections': typeof CorrectionsRoute
  '/credit': typeof CreditRoute
  '/credits': typeof CreditsRoute
  '/invest': typeof InvestRoute
  '/investir': typeof InvestirRoute
  '/kit': typeof KitRoute
  '/membership': typeof MembershipRoute
  '/method': typeof MethodRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/rss-en.xml': typeof RssEnDotxmlRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/tesla': typeof TeslaRoute
  '/today': typeof TodayRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assign': typeof AdminAssignRoute
  '/admin/calibration': typeof AdminCalibrationRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/rejected': typeof AdminRejectedRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/desk-assign': typeof ApiDeskAssignRoute
  '/api/desk-front-page': typeof ApiDeskFrontPageRoute
  '/api/desk-rewrite': typeof ApiDeskRewriteRoute
  '/api/desk-story-status': typeof ApiDeskStoryStatusRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/rss-pull': typeof ApiRssPullRoute
  '/api/score': typeof ApiScoreRoute
  '/api/translate': typeof ApiTranslateRoute
  '/feeds/$section.xml': typeof FeedsSectionDotxmlRoute
  '/story/$slug': typeof StorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/story/$id': typeof AdminStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/about': typeof AboutRoute
  '/acheter': typeof AcheterRoute
  '/advertise': typeof AdvertiseRoute
  '/cambuse': typeof CambuseRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/contest': typeof ContestRoute
  '/cookies': typeof CookiesRoute
  '/corrections': typeof CorrectionsRoute
  '/credit': typeof CreditRoute
  '/credits': typeof CreditsRoute
  '/invest': typeof InvestRoute
  '/investir': typeof InvestirRoute
  '/kit': typeof KitRoute
  '/membership': typeof MembershipRoute
  '/method': typeof MethodRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/rss-en.xml': typeof RssEnDotxmlRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/tesla': typeof TeslaRoute
  '/today': typeof TodayRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assign': typeof AdminAssignRoute
  '/admin/calibration': typeof AdminCalibrationRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/rejected': typeof AdminRejectedRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/desk-assign': typeof ApiDeskAssignRoute
  '/api/desk-front-page': typeof ApiDeskFrontPageRoute
  '/api/desk-rewrite': typeof ApiDeskRewriteRoute
  '/api/desk-story-status': typeof ApiDeskStoryStatusRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/rss-pull': typeof ApiRssPullRoute
  '/api/score': typeof ApiScoreRoute
  '/api/translate': typeof ApiTranslateRoute
  '/feeds/$section.xml': typeof FeedsSectionDotxmlRoute
  '/story/$slug': typeof StorySlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/story/$id': typeof AdminStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/about': typeof AboutRoute
  '/acheter': typeof AcheterRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/cambuse': typeof CambuseRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/contest': typeof ContestRoute
  '/cookies': typeof CookiesRoute
  '/corrections': typeof CorrectionsRoute
  '/credit': typeof CreditRoute
  '/credits': typeof CreditsRoute
  '/invest': typeof InvestRoute
  '/investir': typeof InvestirRoute
  '/kit': typeof KitRoute
  '/membership': typeof MembershipRoute
  '/method': typeof MethodRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/rss-en.xml': typeof RssEnDotxmlRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/tesla': typeof TeslaRoute
  '/today': typeof TodayRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assign': typeof AdminAssignRoute
  '/admin/calibration': typeof AdminCalibrationRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/rejected': typeof AdminRejectedRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/desk-assign': typeof ApiDeskAssignRoute
  '/api/desk-front-page': typeof ApiDeskFrontPageRoute
  '/api/desk-rewrite': typeof ApiDeskRewriteRoute
  '/api/desk-story-status': typeof ApiDeskStoryStatusRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/rss-pull': typeof ApiRssPullRoute
  '/api/score': typeof ApiScoreRoute
  '/api/translate': typeof ApiTranslateRoute
  '/feeds/$section.xml': typeof FeedsSectionDotxmlRoute
  '/story/$slug': typeof StorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/story/$id': typeof AdminStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/about'
    | '/acheter'
    | '/admin'
    | '/advertise'
    | '/cambuse'
    | '/careers'
    | '/contact'
    | '/contest'
    | '/cookies'
    | '/corrections'
    | '/credit'
    | '/credits'
    | '/invest'
    | '/investir'
    | '/kit'
    | '/membership'
    | '/method'
    | '/news-sitemap.xml'
    | '/privacy'
    | '/rankings'
    | '/rss-en.xml'
    | '/rss.xml'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/social'
    | '/submit'
    | '/terms'
    | '/tesla'
    | '/today'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/assign'
    | '/admin/calibration'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/rejected'
    | '/admin/sources'
    | '/admin/translations'
    | '/api/comments'
    | '/api/contact'
    | '/api/desk'
    | '/api/desk-assign'
    | '/api/desk-front-page'
    | '/api/desk-rewrite'
    | '/api/desk-story-status'
    | '/api/ingest'
    | '/api/publish'
    | '/api/rss-pull'
    | '/api/score'
    | '/api/translate'
    | '/feeds/$section.xml'
    | '/story/$slug'
    | '/admin/'
    | '/admin/story/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/about'
    | '/acheter'
    | '/advertise'
    | '/cambuse'
    | '/careers'
    | '/contact'
    | '/contest'
    | '/cookies'
    | '/corrections'
    | '/credit'
    | '/credits'
    | '/invest'
    | '/investir'
    | '/kit'
    | '/membership'
    | '/method'
    | '/news-sitemap.xml'
    | '/privacy'
    | '/rankings'
    | '/rss-en.xml'
    | '/rss.xml'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/social'
    | '/submit'
    | '/terms'
    | '/tesla'
    | '/today'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/assign'
    | '/admin/calibration'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/rejected'
    | '/admin/sources'
    | '/admin/translations'
    | '/api/comments'
    | '/api/contact'
    | '/api/desk'
    | '/api/desk-assign'
    | '/api/desk-front-page'
    | '/api/desk-rewrite'
    | '/api/desk-story-status'
    | '/api/ingest'
    | '/api/publish'
    | '/api/rss-pull'
    | '/api/score'
    | '/api/translate'
    | '/feeds/$section.xml'
    | '/story/$slug'
    | '/admin'
    | '/admin/story/$id'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/about'
    | '/acheter'
    | '/admin'
    | '/advertise'
    | '/cambuse'
    | '/careers'
    | '/contact'
    | '/contest'
    | '/cookies'
    | '/corrections'
    | '/credit'
    | '/credits'
    | '/invest'
    | '/investir'
    | '/kit'
    | '/membership'
    | '/method'
    | '/news-sitemap.xml'
    | '/privacy'
    | '/rankings'
    | '/rss-en.xml'
    | '/rss.xml'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/social'
    | '/submit'
    | '/terms'
    | '/tesla'
    | '/today'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/assign'
    | '/admin/calibration'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/rejected'
    | '/admin/sources'
    | '/admin/translations'
    | '/api/comments'
    | '/api/contact'
    | '/api/desk'
    | '/api/desk-assign'
    | '/api/desk-front-page'
    | '/api/desk-rewrite'
    | '/api/desk-story-status'
    | '/api/ingest'
    | '/api/publish'
    | '/api/rss-pull'
    | '/api/score'
    | '/api/translate'
    | '/feeds/$section.xml'
    | '/story/$slug'
    | '/admin/'
    | '/admin/story/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  AboutRoute: typeof AboutRoute
  AcheterRoute: typeof AcheterRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  CambuseRoute: typeof CambuseRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ContestRoute: typeof ContestRoute
  CookiesRoute: typeof CookiesRoute
  CorrectionsRoute: typeof CorrectionsRoute
  CreditRoute: typeof CreditRoute
  CreditsRoute: typeof CreditsRoute
  InvestRoute: typeof InvestRoute
  InvestirRoute: typeof InvestirRoute
  KitRoute: typeof KitRoute
  MembershipRoute: typeof MembershipRoute
  MethodRoute: typeof MethodRoute
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  PrivacyRoute: typeof PrivacyRoute
  RankingsRoute: typeof RankingsRoute
  RssEnDotxmlRoute: typeof RssEnDotxmlRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialRoute: typeof SocialRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  TeslaRoute: typeof TeslaRoute
  TodayRoute: typeof TodayRoute
  ApiCommentsRoute: typeof ApiCommentsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiDeskAssignRoute: typeof ApiDeskAssignRoute
  ApiDeskFrontPageRoute: typeof ApiDeskFrontPageRoute
  ApiDeskRewriteRoute: typeof ApiDeskRewriteRoute
  ApiDeskStoryStatusRoute: typeof ApiDeskStoryStatusRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiPublishRoute: typeof ApiPublishRoute
  ApiRssPullRoute: typeof ApiRssPullRoute
  ApiScoreRoute: typeof ApiScoreRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  FeedsSectionDotxmlRoute: typeof FeedsSectionDotxmlRoute
  StorySlugRoute: typeof StorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acheter': {
      id: '/acheter'
      path: '/acheter'
      fullPath: '/acheter'
      preLoaderRoute: typeof AcheterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambuse': {
      id: '/cambuse'
      path: '/cambuse'
      fullPath: '/cambuse'
      preLoaderRoute: typeof CambuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest': {
      id: '/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof ContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investir': {
      id: '/investir'
      path: '/investir'
      fullPath: '/investir'
      preLoaderRoute: typeof InvestirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss-en.xml': {
      id: '/rss-en.xml'
      path: '/rss-en.xml'
      fullPath: '/rss-en.xml'
      preLoaderRoute: typeof RssEnDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesla': {
      id: '/tesla'
      path: '/tesla'
      fullPath: '/tesla'
      preLoaderRoute: typeof TeslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assign': {
      id: '/admin/assign'
      path: '/assign'
      fullPath: '/admin/assign'
      preLoaderRoute: typeof AdminAssignRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calibration': {
      id: '/admin/calibration'
      path: '/calibration'
      fullPath: '/admin/calibration'
      preLoaderRoute: typeof AdminCalibrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rejected': {
      id: '/admin/rejected'
      path: '/rejected'
      fullPath: '/admin/rejected'
      preLoaderRoute: typeof AdminRejectedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk-assign': {
      id: '/api/desk-assign'
      path: '/api/desk-assign'
      fullPath: '/api/desk-assign'
      preLoaderRoute: typeof ApiDeskAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk-front-page': {
      id: '/api/desk-front-page'
      path: '/api/desk-front-page'
      fullPath: '/api/desk-front-page'
      preLoaderRoute: typeof ApiDeskFrontPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk-rewrite': {
      id: '/api/desk-rewrite'
      path: '/api/desk-rewrite'
      fullPath: '/api/desk-rewrite'
      preLoaderRoute: typeof ApiDeskRewriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk-story-status': {
      id: '/api/desk-story-status'
      path: '/api/desk-story-status'
      fullPath: '/api/desk-story-status'
      preLoaderRoute: typeof ApiDeskStoryStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rss-pull': {
      id: '/api/rss-pull'
      path: '/api/rss-pull'
      fullPath: '/api/rss-pull'
      preLoaderRoute: typeof ApiRssPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/score': {
      id: '/api/score'
      path: '/api/score'
      fullPath: '/api/score'
      preLoaderRoute: typeof ApiScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/$section.xml': {
      id: '/feeds/$section.xml'
      path: '/feeds/$section.xml'
      fullPath: '/feeds/$section.xml'
      preLoaderRoute: typeof FeedsSectionDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$slug': {
      id: '/story/$slug'
      path: '/story/$slug'
      fullPath: '/story/$slug'
      preLoaderRoute: typeof StorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/story/$id': {
      id: '/admin/story/$id'
      path: '/story/$id'
      fullPath: '/admin/story/$id'
      preLoaderRoute: typeof AdminStoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssignRoute: typeof AdminAssignRoute
  AdminCalibrationRoute: typeof AdminCalibrationRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminRejectedRoute: typeof AdminRejectedRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStoryIdRoute: typeof AdminStoryIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssignRoute: AdminAssignRoute,
  AdminCalibrationRoute: AdminCalibrationRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminRejectedRoute: AdminRejectedRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStoryIdRoute: AdminStoryIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  AboutRoute: AboutRoute,
  AcheterRoute: AcheterRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  CambuseRoute: CambuseRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ContestRoute: ContestRoute,
  CookiesRoute: CookiesRoute,
  CorrectionsRoute: CorrectionsRoute,
  CreditRoute: CreditRoute,
  CreditsRoute: CreditsRoute,
  InvestRoute: InvestRoute,
  InvestirRoute: InvestirRoute,
  KitRoute: KitRoute,
  MembershipRoute: MembershipRoute,
  MethodRoute: MethodRoute,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  PrivacyRoute: PrivacyRoute,
  RankingsRoute: RankingsRoute,
  RssEnDotxmlRoute: RssEnDotxmlRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialRoute: SocialRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  TeslaRoute: TeslaRoute,
  TodayRoute: TodayRoute,
  ApiCommentsRoute: ApiCommentsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiDeskAssignRoute: ApiDeskAssignRoute,
  ApiDeskFrontPageRoute: ApiDeskFrontPageRoute,
  ApiDeskRewriteRoute: ApiDeskRewriteRoute,
  ApiDeskStoryStatusRoute: ApiDeskStoryStatusRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiPublishRoute: ApiPublishRoute,
  ApiRssPullRoute: ApiRssPullRoute,
  ApiScoreRoute: ApiScoreRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  FeedsSectionDotxmlRoute: FeedsSectionDotxmlRoute,
  StorySlugRoute: StorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
